version: "3.3"

services:
  erp-sistema:
    depends_on:
      - erp-database
    hostname: erp-sistema
    image: erp-sistema:0.0.1
    container_name: container_erp_sistema
    ports:
      - "8888:8888"
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 2G
    restart: always
    healthcheck:
      test: curl -f http://erp-sistema:8888/healthcheck || exit 1
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - rede-fluxo-elt
  erp-database:
    hostname: erp-database
    environment:
      MYSQL_ROOT_PASSWORD: d8Uwj1wos64h
      MYSQL_DATABASE: db_erp
    image: mysql:5.7.40
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - erp_database:/var/lib/mysql:rw
    container_name: container_erp_database
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 2G
    restart: always
    healthcheck:
      test: mysqladmin ping -h erp-database -u root -pd8Uwj1wos64h || exit 1
      interval: 30s
      timeout: 20s
      retries: 5
    networks:
      - rede-fluxo-elt
  nifi-server:
    hostname: nifi-server
    image: apache/nifi:1.19.0
    container_name: container_nifi
    ports:
      - "8443:8443"
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: nifi
      SINGLE_USER_CREDENTIALS_PASSWORD: kP8mDnTbXs5H7qL9vFjE3GcA4R6Z2Yy
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 4G
    restart: on-failure
    healthcheck:
      test: wget -q --spider http://nifi-server:8443/nifi-api/system-diagnostics || exit 1
      interval: 60s
      timeout: 40s
      retries: 3
    volumes:
      - ./volumes/nifi/jdbc:/opt/nifi/nifi-current/jdbc
      - nifi_database:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_logs:/opt/nifi/nifi-current/logs
      - nifi_credentials:/opt/nifi/nifi-current/credentials
    networks:
      - rede-fluxo-elt
  nifi-registry:
    depends_on:
      - nifi-server
    hostname: nifi-registry
    container_name: container_nifi_registry
    image: apache/nifi-registry:1.19.0
    ports:
        - "18080:18080"
    environment:
        - LOG_LEVEL=INFO
        - NIFI_REGISTRY_DB_DIR=/opt/nifi-registry/nifi-registry-current/database
        - NIFI_REGISTRY_FLOW_PROVIDER=file
        - NIFI_REGISTRY_FLOW_STORAGE_DIR=/opt/nifi-registry/nifi-registry-current/flow_storage
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 2G
    restart: on-failure
    healthcheck:
      test: wget -q --spider http://nifi-registry:18080/nifi-registry/ || exit 1
      interval: 60s
      timeout: 40s
      retries: 3
    volumes:
        - registry_database:/opt/nifi-registry/nifi-registry-current/database
        - registry_flows:/opt/nifi-registry/nifi-registry-current/flow_storage
    networks:
        - rede-fluxo-elt
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: container_elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - ELASTIC_PASSWORD=nY5AQz37ZZIfMev9
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 4G
    restart: always
    healthcheck:
      test: curl -f http://elasticsearch:9200/_cluster/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
        - rede-fluxo-elt
  kibana:
    depends_on:
       - elasticsearch
    image: kibana:7.17.9
    container_name: container_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=nY5AQz37ZZIfMev9
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 2G
    restart: always
    healthcheck:
      test: curl -f http://kibana:5601/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5601:5601"
    networks:
        - rede-fluxo-elt

volumes:
  nifi_database:
  nifi_flowfile:
  nifi_content:
  nifi_provenance:
  nifi_state:
  nifi_conf:
  nifi_credentials:
  nifi_logs:
  registry_database:
  registry_flows:
  erp_database:
  elastic-data:

networks:
  rede-fluxo-elt:
    driver: bridge
