version: "3.3"
services:
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: container_elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
    deploy:
      resources:
        limits:
          memory: 4G
    restart: always
    #healthcheck:
    #  test: curl -f http://elasticsearch:9200/_cluster/health || exit 1
    #  test: curl -f http://localhost:9200/_cluster/health || exit 1
    #  interval: 30s
    #  timeout: 10s
    #  retries: 5
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
        - rede-fluxo-elt
  kibana:
    depends_on:
       - elasticsearch
    image: kibana:7.17.9
    container_name: container_kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    deploy:
      resources:
        limits:
          memory: 2G
    restart: always
    #healthcheck:
    #  test: curl -f http://kibana:9200/_cluster/health || exit 1
    #  test: curl -f http://localhost:9200/_cluster/health || exit 1
    #  interval: 30s
    #  timeout: 10s
    #  retries: 5
    ports:
      - "5601:5601"
    networks:
        - rede-fluxo-elt

volumes:
  elastic-data:

networks:
  rede-fluxo-elt:
    driver: bridge