version: "3.3"

services:
  erp-app:
    depends_on:
      - erp-database
    hostname: erp-app
    image: erp-app:0.0.1
    container_name: erp-app
    ports:
      - "8888:8888"
    deploy:
      resources:
        limits:
          memory: 2G
    restart: always
    healthcheck:
      test: curl -f http://erp-app:8888/healthcheck
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - rede-fluxo-elt
  erp-database:
    hostname: erp-database
    environment:
      MYSQL_ROOT_PASSWORD: d8Uwj1wos64h
      MYSQL_DATABASE: db_erp
    image: mysql:5.7.40
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./erp-database:/var/lib/mysql:rw
    container_name: erp-database
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 2G
    restart: always
    networks:
      - rede-fluxo-elt

networks:
  rede-fluxo-elt:
    driver: bridge
